// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v1 "shorturl/api/internal/handler/v1"
	"shorturl/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/shorten",
					Handler: v1.ShortenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/expand",
					Handler: v1.ExpandHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
